openapi: 3.0.1
servers:
- url: /
paths:
  current-identity-edge-routers:
    get:
      tags:
      - Current Identity
      - Edge Router
      summary: Return this list of Edge Routers the identity has access to
      description: |
        Lists the Edge Routers that the current identity has access to via policies. The data returned
        includes their address and online status
      operationId: getCurrentIdentityEdgeRouters
      responses:
        "200":
          $ref: '#/components/responses/listCurrentIdentityEdgeRouters'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
components:
  schemas:
    listCurrentIdentityEdgeRoutersEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/currentIdentityEdgeRouterList'
    currentIdentityEdgeRouterList:
      type: array
      description: A list of edge router resources
      items:
        $ref: '#/components/schemas/currentIdentityEdgeRouterDetail'
    currentIdentityEdgeRouterDetail:
      description: A detail edge router resource
      allOf:
      - $ref: ../shared/base-entity.yml#/definitions/baseEntity
      - $ref: ../shared/edge-routers.yml#/definitions/commonEdgeRouterProperties
  responses:
    listCurrentIdentityEdgeRouters:
      description: A list of edge routers
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listCurrentIdentityEdgeRoutersEnvelope'
x-original-swagger-version: null
