openapi: 3.0.1
servers:
- url: /
paths:
  current-api-session-service-updates:
    get:
      tags:
      - Current API Session
      - Services
      summary: Returns data indicating whether a client should updates it service
        list
      description: |
        Retrieves data indicating the last time data relevant to this API Session was altered that would necessitate
        service refreshes.
      operationId: listServiceUpdates
      responses:
        "200":
          $ref: '#/components/responses/listCurrentApiSessionServiceUpdates'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
components:
  schemas:
    listCurrentApiSessionServiceUpdatesEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/CurrentApiSessionServiceUpdateList'
    CurrentApiSessionServiceUpdateList:
      required:
      - lastChangeAt
      type: object
      properties:
        lastChangeAt:
          type: string
          format: date-time
  responses:
    listCurrentApiSessionServiceUpdates:
      description: Data indicating necessary service updates
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listCurrentApiSessionServiceUpdatesEnvelope'
x-original-swagger-version: null
