openapi: 3.0.1
servers:
- url: /
paths:
  posture-response:
    post:
      tags:
      - Posture Checks
      summary: Submit a posture response to a posture query
      description: Submits posture responses
      operationId: createPostureResponse
      requestBody:
        description: A Posture Response
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/postureResponseCreate'
        required: true
      responses:
        "201":
          $ref: '#/components/responses/postureResponse'
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: postureResponse
  posture-response-bulk:
    post:
      tags:
      - Posture Checks
      summary: Submit multiple posture responses
      description: Submits posture responses
      operationId: createPostureResponseBulk
      requestBody:
        description: A Posture Response
        content:
          '*/*':
            schema:
              type: array
              items:
                $ref: '#/components/schemas/postureResponseCreate'
        required: true
      responses:
        "200":
          $ref: '#/components/responses/postureResponse'
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: postureResponse
components:
  schemas:
    postureResponseEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/postureResponse'
    postureResponseService:
      required:
      - id
      - name
      - postureQueryType
      - timeout
      - timeoutRemaining
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        postureQueryType:
          type: string
        timeout:
          type: integer
        timeoutRemaining:
          type: integer
    postureResponse:
      required:
      - services
      type: object
      properties:
        services:
          type: array
          items:
            $ref: '#/components/schemas/postureResponseService'
    postureResponseCreate:
      required:
      - id
      - typeId
      type: object
      properties:
        id:
          type: string
        typeId:
          $ref: ../shared/posture-checks.yml#/definitions/postureCheckType
      discriminator:
        propertyName: typeId
    postureResponseOperatingSystemCreate:
      allOf:
      - $ref: '#/components/schemas/postureResponseCreate'
      - required:
        - type
        - version
        type: object
        properties:
          type:
            type: string
          version:
            type: string
          build:
            type: string
      x-class: OS
    postureResponseDomainCreate:
      allOf:
      - $ref: '#/components/schemas/postureResponseCreate'
      - required:
        - domain
        type: object
        properties:
          domain:
            type: string
      x-class: DOMAIN
    postureResponseMacAddressCreate:
      allOf:
      - $ref: '#/components/schemas/postureResponseCreate'
      - required:
        - macAddresses
        type: object
        properties:
          macAddresses:
            type: array
            items:
              type: string
      x-class: MAC
    postureResponseProcessCreate:
      allOf:
      - $ref: '#/components/schemas/postureResponseCreate'
      - type: object
        properties:
          path:
            type: string
          isRunning:
            type: boolean
          hash:
            type: string
          signerFingerprints:
            type: array
            items:
              type: string
      x-class: PROCESS
    postureResponseEndpointStateCreate:
      allOf:
      - $ref: '#/components/schemas/postureResponseCreate'
      - type: object
        properties:
          unlocked:
            type: boolean
          woken:
            type: boolean
      x-class: ENDPOINT_STATE
  responses:
    postureResponse:
      description: Contains a list of services that have had their timers altered
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/postureResponseEnvelope'
x-original-swagger-version: null
