openapi: 3.0.1
servers:
- url: /
paths:
  protocols:
    get:
      tags:
      - Informational
      summary: Return a list of the listening Edge protocols
      operationId: listProtocols
      responses:
        "200":
          $ref: '#/components/responses/listProtocols'
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security: []
components:
  schemas:
    listProtocolsEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/listProtocols'
    listProtocols:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/protocol'
    protocol:
      required:
      - address
      type: object
      properties:
        address:
          type: string
  responses:
    listProtocols:
      description: A list of supported Edge protocols
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listProtocolsEnvelope'
x-original-swagger-version: null
