openapi: 3.0.1
servers:
- url: /
paths:
  services:
    get:
      tags:
      - Service
      summary: List services
      description: |
        Retrieves a list of config resources; supports filtering, sorting, and pagination. Requires admin access.
      operationId: listServices
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      - $ref: ../shared/parameters.yml#/configTypes
      - $ref: ../shared/parameters.yml#/roleFilter
      - $ref: ../shared/parameters.yml#/roleSemantic
      responses:
        "200":
          $ref: ../shared/services.yml#/responses/listServices
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
  services-id:
    get:
      tags:
      - Service
      summary: Retrieves a single service
      description: Retrieves a single service by id. Requires admin access.
      operationId: detailService
      responses:
        "200":
          $ref: ../shared/services.yml#/responses/detailService
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
  services-id-terminators:
    get:
      tags:
      - Service
      summary: List of terminators assigned to a service
      description: |
        Retrieves a list of terminator resources that are assigned specific service; supports filtering, sorting, and pagination.
      operationId: listServiceTerminators
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      responses:
        "200":
          $ref: '#/components/responses/listClientTerminators'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
  services-id-edge-routers:
    get:
      tags:
      - Service
      summary: List of edge routers permitted to handle traffic for the specified
        service
      description: |
        Retrieves the list of edge routers permitted to handle traffic for the specified service
      operationId: listServiceEdgeRouters
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      - name: session-token
        in: header
        description: "an optional JWT token use to authenticate the request. If provided,\
          \ the token must be valid else a not authorized response is returned."
        schema:
          type: string
      responses:
        "200":
          $ref: '#/components/responses/listServiceEdgeRouters'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
components:
  schemas:
    listServiceEdgeRoutersEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: ../shared/edge-routers.yml#/definitions/serviceEdgeRouters
    listClientTerminatorsEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/terminatorClientList'
    terminatorClientList:
      type: array
      items:
        $ref: '#/components/schemas/terminatorClientDetail'
    terminatorClientDetail:
      allOf:
      - $ref: ../shared/base-entity.yml#/definitions/baseEntity
      - required:
        - identity
        - routerId
        - service
        - serviceId
        type: object
        properties:
          serviceId:
            type: string
          service:
            $ref: ../shared/base-entity.yml#/definitions/entityRef
          routerId:
            type: string
          identity:
            type: string
  responses:
    listClientTerminators:
      description: A list of terminators
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listClientTerminatorsEnvelope'
    listServiceEdgeRouters:
      description: A list of edge routers suitable for dialing or binding the specified
        service by the authenticated identity
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listServiceEdgeRoutersEnvelope'
x-original-swagger-version: null
