openapi: 3.0.1
servers:
- url: /
paths:
  sessions:
    get:
      tags:
      - Session
      summary: List sessions
      description: |
        Retrieves a list of active sessions resources; supports filtering, sorting, and pagination.

        Sessions are tied to an API session and are moved when an API session times out or logs out. Active sessions
        (i.e. Ziti SDK connected to an edge router) will keep the session and API session marked as active.
      operationId: listSessions
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      responses:
        "200":
          $ref: ../shared/sessions.yml#/responses/listSessions
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    post:
      tags:
      - Session
      summary: Create a session resource
      description: Create a session resource.
      operationId: createSession
      requestBody:
        description: A session to create
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/sessionCreate'
        required: true
      responses:
        "201":
          $ref: '#/components/responses/sessionCreateResponse'
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: session
  sessions-id:
    get:
      tags:
      - Session
      summary: Retrieves a single session
      description: Retrieves a single session by id.
      operationId: detailSession
      responses:
        "200":
          $ref: ../shared/sessions.yml#/responses/detailSession
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    delete:
      tags:
      - Session
      summary: Delete a session
      description: Delete a session by id.
      operationId: deleteSession
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/deleteResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "409":
          $ref: ../shared/standard-responses.yml#/responses/cannotDeleteReferencedResourceResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
components:
  schemas:
    sessionCreateEnvelope:
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: ../shared/sessions.yml#/definitions/sessionDetail
    sessionCreate:
      type: object
      properties:
        serviceId:
          type: string
        type:
          $ref: ../shared/base-entity.yml#/definitions/dialBind
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
  responses:
    sessionCreateResponse:
      description: The create request was successful and the resource has been added
        at the following location
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/sessionCreateEnvelope'
x-original-swagger-version: null
