openapi: 3.0.1
servers:
- url: /
paths:
  authenticators:
    get:
      tags:
      - Authenticator
      summary: List authenticators
      description: |
        Returns a list of authenticators associated to identities. The resources can be sorted, filtered, and paginated.
        This endpoint requires admin access.
      operationId: listAuthenticators
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      responses:
        "200":
          $ref: ../shared/authenticators.yml#/responses/listAuthenticators
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    post:
      tags:
      - Authenticator
      summary: Creates an authenticator
      description: |
        Creates an authenticator for a specific identity. Requires admin access.
      operationId: createAuthenticator
      requestBody:
        description: A Authenticator create object
        content:
          '*/*':
            schema:
              $ref: ../shared/authenticators.yml#/definitions/authenticatorCreate
        required: true
      responses:
        "201":
          $ref: ../shared/standard-responses.yml#/responses/createResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: authenticator
  authenticators-id:
    get:
      tags:
      - Authenticator
      summary: Retrieves a single authenticator
      description: Retrieves a single authenticator by id. Requires admin access.
      operationId: detailAuthenticator
      responses:
        "200":
          $ref: ../shared/authenticators.yml#/responses/detailAuthenticator
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    put:
      tags:
      - Authenticator
      summary: Update all fields on an authenticator
      description: Update all fields on an authenticator by id. Requires admin access.
      operationId: updateAuthenticator
      requestBody:
        description: An authenticator put object
        content:
          '*/*':
            schema:
              $ref: ../shared/authenticators.yml#/definitions/authenticatorUpdate
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/updateResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: authenticator
    delete:
      tags:
      - Authenticator
      summary: Delete an Authenticator
      description: |
        Delete an authenticator by id. Deleting all authenticators for an identity will make it impossible to log in.
        Requires admin access.
      operationId: deleteAuthenticator
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/deleteResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    patch:
      tags:
      - Authenticator
      summary: Update the supplied fields on an authenticator
      description: Update the supplied fields on an authenticator by id. Requires
        admin access.
      operationId: patchAuthenticator
      requestBody:
        description: An authenticator patch object
        content:
          '*/*':
            schema:
              $ref: ../shared/authenticators.yml#/definitions/authenticatorPatch
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/patchResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: authenticator
    parameters:
    - $ref: ../shared/parameters.yml#/id
  authenticators-id-re-enroll:
    post:
      tags:
      - Authenticator
      summary: Reverts an authenticator to an enrollment
      description: "Allows an authenticator to be reverted to an enrollment and allows\
        \ re-enrollment to occur. On success the \ncreated enrollment record response\
        \ is provided and the source authenticator record will be deleted. The \n\
        enrollment created depends on the authenticator. UPDB authenticators result\
        \ in UPDB enrollments, CERT\nauthenticators result in OTT enrollments, CERT\
        \ + CA authenticators result in OTTCA enrollments.\n"
      operationId: reEnrollAuthenticator
      requestBody:
        description: A reEnrollment request
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/reEnroll'
        required: true
      responses:
        "201":
          $ref: ../shared/standard-responses.yml#/responses/createResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: reEnroll
    parameters:
    - $ref: ../shared/parameters.yml#/id
components:
  schemas:
    reEnroll:
      required:
      - expiresAt
      type: object
      properties:
        expiresAt:
          type: string
          format: date-time
x-original-swagger-version: null
