openapi: 3.0.1
servers:
- url: /
paths:
  cas:
    get:
      tags:
      - Certificate Authority
      summary: List CAs
      description: "Retrieves a list of CA resources; supports filtering, sorting,\
        \ and pagination. Requires admin access."
      operationId: listCas
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      responses:
        "200":
          $ref: '#/components/responses/listCas'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    post:
      tags:
      - Certificate Authority
      summary: Creates a CA
      description: Creates a CA in an unverified state. Requires admin access.
      operationId: createCa
      requestBody:
        description: A CA to create
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/caCreate'
        required: true
      responses:
        "201":
          $ref: ../shared/standard-responses.yml#/responses/createResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: ca
  cas-id:
    get:
      tags:
      - Certificate Authority
      summary: Retrieves a single CA
      description: Retrieves a single CA by id. Requires admin access.
      operationId: detailCa
      responses:
        "200":
          $ref: '#/components/responses/detailCa'
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    put:
      tags:
      - Certificate Authority
      summary: Update all fields on a CA
      description: Update all fields on a CA by id. Requires admin access.
      operationId: updateCa
      requestBody:
        description: A CA update object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/caUpdate'
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/updateResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: ca
    delete:
      tags:
      - Certificate Authority
      summary: Delete a CA
      description: |
        Delete a CA by id. Deleting a CA will delete its associated certificate authenticators. This can make it
        impossible for identities to authenticate if they no longer have any valid authenticators. Requires admin access.
      operationId: deleteCa
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/deleteResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    patch:
      tags:
      - Certificate Authority
      summary: Update the supplied fields on a CA
      description: Update only the supplied fields on a CA by id. Requires admin access.
      operationId: patchCa
      requestBody:
        description: A CA patch object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/caPatch'
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/patchResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: ca
    parameters:
    - $ref: ../shared/parameters.yml#/id
  cas-id-jwt:
    get:
      tags:
      - Certificate Authority
      summary: Retrieve the enrollment JWT for a CA
      description: |
        For CA auto enrollment, the enrollment JWT is static and provided on each CA resource. This endpoint provides
        the jwt as a text response.
      operationId: getCaJwt
      responses:
        "200":
          description: The result is the JWT text to validate the CA
          content:
            application/jwt:
              schema:
                type: string
              example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbSI6ImNhIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6MTI
                4MC8ifQ.Ot6lhNBSOw8ygHytdI5l7WDf9EWadOj44UPvJ0c-8mJ54fClWM3uMZrAHSSfV6KmOSZOeBBJe4VlNyoD-_MOECP0BzYSnSQP3E
                zJb0VlM-fFmGcKNGW157icyZNISfO43JL_Lw2QPBzTgikqSIj9eZnocC3BeAmZCHsVznnLfHWqDldcmuxnu-5MNOSrWV1x9iVcgLFlLHXK
                2PLA4qIiZmlQTrQjpHJmUaoJ07mnj8hMKzxB3wBG8kpazjEo7HDRCO06aBH4eqFgf_l0iT8Dzcb31jquWMGUoSXPhf4lVJh_FiNcR1wVx-
                UiHLbG5h23Aqf1UJF-F38rc1FElKz0Zg
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
  cas-id-verify:
    post:
      tags:
      - Certificate Authority
      summary: Verify a CA
      description: |
        Allows a CA to become verified by submitting a certificate in PEM format that has been signed by the target CA.
        The common name on the certificate must match the verificationToken property of the CA. Unverfieid CAs can not
        be used for enrollment/authentication. Requires admin access.
      operationId: verifyCa
      requestBody:
        description: A PEM formatted certificate signed by the target CA with the
          common name matching the CA's validationToken
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/emptyResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: certificate
    parameters:
    - $ref: ../shared/parameters.yml#/id
components:
  schemas:
    externalIdClaim:
      required:
      - index
      - location
      - matcher
      - matcherCriteria
      - parser
      - parserCriteria
      type: object
      properties:
        location:
          type: string
          nullable: true
          enum:
          - COMMON_NAME
          - SAN_URI
          - SAN_EMAIL
        matcher:
          type: string
          nullable: true
          enum:
          - ALL
          - PREFIX
          - SUFFIX
          - SCHEME
        matcherCriteria:
          type: string
          nullable: true
        parser:
          type: string
          nullable: true
          enum:
          - NONE
          - SPLIT
        parserCriteria:
          type: string
          nullable: true
        index:
          type: integer
          nullable: true
    externalIdClaimPatch:
      type: object
      properties:
        location:
          type: string
          nullable: true
          enum:
          - COMMON_NAME
          - SAN_URI
          - SAN_EMAIL
        matcher:
          type: string
          nullable: true
          enum:
          - ALL
          - PREFIX
          - SUFFIX
          - SCHEME
        matcherCriteria:
          type: string
          nullable: true
        parser:
          type: string
          nullable: true
          enum:
          - NONE
          - SPLIT
        parserCriteria:
          type: string
          nullable: true
        index:
          type: integer
          nullable: true
    listCasEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/caList'
    detailCaEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/caDetail'
    caList:
      type: array
      description: An array of Certificate Authority (CA) resources
      items:
        $ref: '#/components/schemas/caDetail'
    caDetail:
      description: A Certificate Authority (CA) resource
      allOf:
      - $ref: ../shared/base-entity.yml#/definitions/baseEntity
      - required:
        - certPem
        - fingerprint
        - identityNameFormat
        - identityRoles
        - isAuthEnabled
        - isAutoCaEnrollmentEnabled
        - isOttCaEnrollmentEnabled
        - isVerified
        - name
        type: object
        properties:
          name:
            type: string
          fingerprint:
            type: string
          certPem:
            type: string
          isVerified:
            type: boolean
            example: false
          verificationToken:
            type: string
            format: uuid
          isAutoCaEnrollmentEnabled:
            type: boolean
            example: true
          isOttCaEnrollmentEnabled:
            type: boolean
            example: true
          isAuthEnabled:
            type: boolean
            example: true
          identityRoles:
            $ref: ../shared/base-entity.yml#/definitions/roles
          identityNameFormat:
            type: string
          externalIdClaim:
            $ref: '#/components/schemas/externalIdClaim'
    caCreate:
      required:
      - certPem
      - identityRoles
      - isAuthEnabled
      - isAutoCaEnrollmentEnabled
      - isOttCaEnrollmentEnabled
      - name
      type: object
      properties:
        name:
          type: string
          example: Test 3rd Party External CA
        isAutoCaEnrollmentEnabled:
          type: boolean
          example: true
        isAuthEnabled:
          type: boolean
          example: true
        isOttCaEnrollmentEnabled:
          type: boolean
          example: true
        certPem:
          type: string
          example: |
            -----BEGIN CERTIFICATE-----
            MIICUjCCAdmgAwIBAgIJANooo7NB+dZZMAoGCCqGSM49BAMCMF4xCzAJBgNVBAYT
            AlVTMQswCQYDVQQIDAJOQzETMBEGA1UECgwKTmV0Rm91bmRyeTEtMCsGA1UEAwwk
            TmV0Rm91bmRyeSBaaXRpIEV4dGVybmFsIEFQSSBSb290IENBMB4XDTE4MTExNTEy
            NTcwOVoXDTM4MTExMDEyNTcwOVowXjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk5D
            MRMwEQYDVQQKDApOZXRGb3VuZHJ5MS0wKwYDVQQDDCROZXRGb3VuZHJ5IFppdGkg
            RXh0ZXJuYWwgQVBJIFJvb3QgQ0EwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAARwq61Z
            Iaqbaw0PDt3frJZaHjkxfZhwYrykI1GlbRNd/jix03lVG9qvpN5Og9fQfFFcFmD/
            3vCE9S6O0npm0mADQxcBcxbMRAH5dtBuCuiJW6qAAbPgiM32vqSxBiFt0KejYzBh
            MB0GA1UdDgQWBBRx1OVGuc/jdltDc8YBtkw8Tbr4fjAfBgNVHSMEGDAWgBRx1OVG
            uc/jdltDc8YBtkw8Tbr4fjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIB
            hjAKBggqhkjOPQQDAgNnADBkAjBDRxNZUaIVpkQKnAgJukl3ysd3/i7Z6hDyIEms
            kllz/+ZvmdBp9iedV5o5BvJUggACMCv+UBFlJH7pmsOCo/F45Kk178YsCC7gaMxE
            1ZG1zveyMvsYsH04C9FndE6w2MLvlA==
            -----END CERTIFICATE-----
        identityRoles:
          $ref: ../shared/base-entity.yml#/definitions/roles
        identityNameFormat:
          type: string
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
        externalIdClaim:
          $ref: '#/components/schemas/externalIdClaim'
      description: A create Certificate Authority (CA) object
    caUpdate:
      required:
      - identityNameFormat
      - identityRoles
      - isAuthEnabled
      - isAutoCaEnrollmentEnabled
      - isOttCaEnrollmentEnabled
      - name
      type: object
      properties:
        name:
          type: string
          example: My CA
        isAutoCaEnrollmentEnabled:
          type: boolean
          example: true
        isOttCaEnrollmentEnabled:
          type: boolean
          example: true
        isAuthEnabled:
          type: boolean
          example: true
        identityRoles:
          $ref: ../shared/base-entity.yml#/definitions/roles
        identityNameFormat:
          type: string
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
        externalIdClaim:
          $ref: '#/components/schemas/externalIdClaim'
    caPatch:
      type: object
      properties:
        name:
          type: string
          nullable: true
          example: My CA
        isAutoCaEnrollmentEnabled:
          type: boolean
          nullable: true
          example: true
        isOttCaEnrollmentEnabled:
          type: boolean
          nullable: true
          example: true
        isAuthEnabled:
          type: boolean
          nullable: true
          example: true
        identityRoles:
          $ref: ../shared/base-entity.yml#/definitions/roles
        identityNameFormat:
          type: string
          nullable: true
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
        externalIdClaim:
          $ref: '#/components/schemas/externalIdClaimPatch'
  responses:
    listCas:
      description: A list of Certificate Authorities (CAs)
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listCasEnvelope'
    detailCa:
      description: A singular Certificate Authority (CA) resource
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailCaEnvelope'
x-original-swagger-version: null
