openapi: 3.0.1
servers:
- url: /
paths:
  database-snapshot:
    post:
      tags:
      - Database
      summary: Create a new database snapshot
      description: Create a new database snapshot. Requires admin access.
      operationId: createDatabaseSnapshot
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/emptyResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
  database-check-data-integrity:
    post:
      tags:
      - Database
      summary: Starts a data integrity scan on the datastore
      description: "Starts a data integrity scan on the datastore. Requires admin\
        \ access. Only once instance may run at a time, including runs of fixDataIntegrity."
      operationId: checkDataIntegrity
      responses:
        "202":
          $ref: ../shared/standard-responses.yml#/responses/emptyResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
  database-fix-data-integrity:
    post:
      tags:
      - Database
      summary: "Runs a data integrity scan on the datastore, attempts to fix any issues\
        \ it can and returns any found issues"
      description: "Runs a data integrity scan on the datastore, attempts to fix any\
        \ issues it can, and returns any found issues. Requires admin access. Only\
        \ once instance may run at a time, including runs of checkDataIntegrity."
      operationId: fixDataIntegrity
      responses:
        "202":
          $ref: ../shared/standard-responses.yml#/responses/emptyResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
  database-data-integrity-results:
    get:
      tags:
      - Database
      summary: Returns any results found from in-progress integrity checks
      description: Returns any results found from in-progress integrity checks. Requires
        admin access.
      operationId: dataIntegrityResults
      responses:
        "200":
          $ref: '#/components/responses/dataIntegrityCheckResult'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
components:
  schemas:
    dataIntegrityCheckResultEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/dataIntegrityCheckDetails'
    dataIntegrityCheckDetails:
      required:
      - endTime
      - error
      - fixingErrors
      - inProgress
      - results
      - startTime
      - tooManyErrors
      type: object
      properties:
        inProgress:
          type: boolean
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        fixingErrors:
          type: boolean
        error:
          type: string
        tooManyErrors:
          type: boolean
        results:
          $ref: '#/components/schemas/dataIntegrityCheckDetailList'
    dataIntegrityCheckDetailList:
      type: array
      items:
        $ref: '#/components/schemas/dataIntegrityCheckDetail'
    dataIntegrityCheckDetail:
      required:
      - description
      - fixed
      type: object
      properties:
        description:
          type: string
        fixed:
          type: boolean
  responses:
    dataIntegrityCheckResult:
      description: A list of data integrity issues found
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/dataIntegrityCheckResultEnvelope'
x-original-swagger-version: null
