openapi: 3.0.1
servers:
- url: /
paths:
  edge-routers:
    get:
      tags:
      - Edge Router
      summary: List edge routers
      description: |
        Retrieves a list of edge router resources; supports filtering, sorting, and pagination. Requires admin access.
      operationId: listEdgeRouters
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      - $ref: ../shared/parameters.yml#/roleFilter
      - $ref: ../shared/parameters.yml#/roleSemantic
      responses:
        "200":
          $ref: '#/components/responses/listEdgeRouters'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    post:
      tags:
      - Edge Router
      summary: Create an edge router
      description: Create a edge router resource. Requires admin access.
      operationId: createEdgeRouter
      requestBody:
        description: A edge router to create
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/edgeRouterCreate'
        required: true
      responses:
        "201":
          $ref: ../shared/standard-responses.yml#/responses/createResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: edgeRouter
  edge-routers-id:
    get:
      tags:
      - Edge Router
      summary: Retrieves a single edge router
      description: Retrieves a single edge router by id. Requires admin access.
      operationId: detailEdgeRouter
      responses:
        "200":
          $ref: '#/components/responses/detailEdgeRouter'
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    put:
      tags:
      - Edge Router
      summary: Update all fields on an edge router
      description: Update all fields on an edge router by id. Requires admin access.
      operationId: updateEdgeRouter
      requestBody:
        description: An edge router update object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/edgeRouterUpdate'
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/updateResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: edgeRouter
    delete:
      tags:
      - Edge Router
      summary: Delete an edge router
      description: Delete an edge router by id. Requires admin access.
      operationId: deleteEdgeRouter
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/deleteResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "409":
          $ref: ../shared/standard-responses.yml#/responses/cannotDeleteReferencedResourceResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    patch:
      tags:
      - Edge Router
      summary: Update the supplied fields on an edge router
      description: Update the supplied fields on an edge router. Requires admin access.
      operationId: patchEdgeRouter
      requestBody:
        description: An edge router patch object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/edgeRouterPatch'
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/patchResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: edgeRouter
    parameters:
    - $ref: ../shared/parameters.yml#/id
  edge-routers-id-edge-router-policies:
    get:
      tags:
      - Edge Router
      summary: List the edge router policies that affect an edge router
      description: Retrieves a list of edge router policies that apply to the specified
        edge router.
      operationId: listEdgeRouterEdgeRouterPolicies
      responses:
        "200":
          $ref: edge-router-policies.yml#/responses/listEdgeRouterPolicies
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
  edge-routers-id-identities:
    get:
      tags:
      - Edge Router
      summary: List associated identities
      description: |
        Retrieves a list of identities that may access services via the given edge router. Supports filtering, sorting, and pagination. Requires admin access.
      operationId: listEdgeRouterIdentities
      responses:
        "200":
          $ref: identities.yml#/responses/listIdentities
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
  edge-routers-id-service-edge-router-policies:
    get:
      tags:
      - Edge Router
      summary: List the service policies that affect an edge router
      description: Retrieves a list of service policies policies that apply to the
        specified edge router.
      operationId: listEdgeRouterServiceEdgeRouterPolicies
      responses:
        "200":
          $ref: service-policies.yml#/responses/listServicePolicies
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
  edge-routers-id-services:
    get:
      tags:
      - Edge Router
      summary: List associated services
      description: |
        Retrieves a list of services that may be accessed via the given edge router. Supports filtering, sorting, and pagination. Requires admin access.
      operationId: listEdgeRouterServices
      responses:
        "200":
          $ref: ../shared/services.yml#/responses/listServices
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
  edge-routers-id-re-enroll:
    post:
      tags:
      - Edge Router
      summary: Re-enroll an edge router
      description: |
        Removes current certificate based authentication mechanisms and reverts the edge router into a state where enrollment must be performed.
        The router retains all other properties and associations. If the router is currently connected, it will be disconnected and any
        attemps to reconnect will fail until the enrollment process is completed with the newly generated JWT.

        If the edge router has an existing outstanding enrollment JWT it will be replaced. The previous JWT will no longer be usable to
        complete the enrollment process.
      operationId: reEnrollEdgeRouter
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/emptyResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
components:
  schemas:
    listEdgeRoutersEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/edgeRouterList'
    detailedEdgeRouterEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/edgeRouterDetail'
    edgeRouterCreate:
      required:
      - name
      type: object
      properties:
        name:
          type: string
        isTunnelerEnabled:
          type: boolean
        cost:
          maximum: 65535
          minimum: 0
          type: integer
          nullable: true
        noTraversal:
          type: boolean
          nullable: true
        disabled:
          type: boolean
          nullable: true
        roleAttributes:
          $ref: ../shared/base-entity.yml#/definitions/attributes
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
        appData:
          $ref: ../shared/base-entity.yml#/definitions/tags
      description: An edge router create object
    edgeRouterUpdate:
      required:
      - name
      type: object
      properties:
        name:
          type: string
        isTunnelerEnabled:
          type: boolean
        cost:
          maximum: 65535
          minimum: 0
          type: integer
          nullable: true
        noTraversal:
          type: boolean
          nullable: true
        disabled:
          type: boolean
          nullable: true
        roleAttributes:
          $ref: ../shared/base-entity.yml#/definitions/attributes
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
        appData:
          $ref: ../shared/base-entity.yml#/definitions/tags
      description: An edge router update object
    edgeRouterPatch:
      type: object
      properties:
        name:
          type: string
          nullable: true
        isTunnelerEnabled:
          type: boolean
        cost:
          maximum: 65535
          minimum: 0
          type: integer
          nullable: true
        noTraversal:
          type: boolean
          nullable: true
        disabled:
          type: boolean
          nullable: true
        roleAttributes:
          $ref: ../shared/base-entity.yml#/definitions/attributes
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
        appData:
          $ref: ../shared/base-entity.yml#/definitions/tags
      description: An edge router patch object
    edgeRouterList:
      type: array
      description: A list of edge router resources
      items:
        $ref: '#/components/schemas/edgeRouterDetail'
    edgeRouterDetail:
      description: A detail edge router resource
      allOf:
      - $ref: ../shared/base-entity.yml#/definitions/baseEntity
      - $ref: ../shared/edge-routers.yml#/definitions/commonEdgeRouterProperties
      - required:
        - isTunnelerEnabled
        - isVerified
        - roleAttributes
        type: object
        properties:
          isVerified:
            type: boolean
          enrollmentToken:
            type: string
            nullable: true
          enrollmentJwt:
            type: string
            nullable: true
          enrollmentCreatedAt:
            type: string
            format: date-time
            nullable: true
          enrollmentExpiresAt:
            type: string
            format: date-time
            nullable: true
          roleAttributes:
            $ref: ../shared/base-entity.yml#/definitions/attributes
          fingerprint:
            type: string
          certPem:
            type: string
            nullable: true
            x-omitempty: false
          unverifiedFingerprint:
            type: string
            nullable: true
            x-omitempty: false
          unverifiedCertPem:
            type: string
            nullable: true
            x-omitempty: false
          versionInfo:
            $ref: ../shared/version.yml#/definitions/versionInfo
          isTunnelerEnabled:
            type: boolean
    routerEntityRef:
      allOf:
      - $ref: ../shared/base-entity.yml#/definitions/entityRef
      - required:
        - isOnline
        type: object
        properties:
          isOnline:
            type: boolean
  responses:
    listEdgeRouters:
      description: A list of edge routers
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listEdgeRoutersEnvelope'
    detailEdgeRouter:
      description: A singular edge router resource
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailedEdgeRouterEnvelope'
x-original-swagger-version: null
