openapi: 3.0.1
servers:
- url: /
paths:
  enrollments:
    get:
      tags:
      - Enrollment
      summary: List outstanding enrollments
      description: |
        Retrieves a list of outstanding enrollments; supports filtering, sorting, and pagination. Requires admin access.
      operationId: listEnrollments
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      responses:
        "200":
          $ref: '#/components/responses/listEnrollments'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    post:
      tags:
      - Enrollment
      summary: Create an outstanding enrollment for an identity
      description: "Creates a new OTT, OTTCA, or UPDB enrollment for a specific identity.\
        \ If an enrollment of the same type is already outstanding the request will\
        \ fail with a 409 conflict. If desired, an existing enrollment can be refreshed\
        \ by `enrollments/:id/refresh` or deleted."
      operationId: createEnrollment
      requestBody:
        description: An enrollment to create
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/enrollmentCreate'
        required: true
      responses:
        "201":
          $ref: ../shared/standard-responses.yml#/responses/createResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "409":
          $ref: ../shared/standard-responses.yml#/responses/conflictResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: enrollment
  enrollments-id:
    get:
      tags:
      - Enrollment
      summary: Retrieves an outstanding enrollment
      description: Retrieves a single outstanding enrollment by id. Requires admin
        access.
      operationId: detailEnrollment
      responses:
        "200":
          $ref: '#/components/responses/detailEnrollment'
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    delete:
      tags:
      - Enrollment
      summary: Delete an outstanding enrollment
      description: Delete an outstanding enrollment by id. Requires admin access.
      operationId: deleteEnrollment
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/deleteResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
  enrollments-id-refresh:
    post:
      tags:
      - Enrollment
      summary: Refreshes an enrollment record's expiration window
      description: "For expired or unexpired enrollments, reset the expiration window.\
        \ A new JWT will be generated and must be used for the enrollment."
      operationId: refreshEnrollment
      requestBody:
        description: An enrollment refresh request
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/enrollmentRefresh'
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/createResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: refresh
    parameters:
    - $ref: ../shared/parameters.yml#/id
components:
  schemas:
    listEnrollmentsEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/enrollmentList'
    detailEnrollmentEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/enrollmentDetail'
    enrollmentList:
      type: array
      description: An array of enrollment resources
      items:
        $ref: '#/components/schemas/enrollmentDetail'
    enrollmentDetail:
      description: |
        An enrollment object. Enrollments are tied to identities and potentially a CA. Depending on the
        method, different fields are utilized. For example ottca enrollments use the `ca` field and updb enrollments
        use the username field, but not vice versa.
      allOf:
      - $ref: ../shared/base-entity.yml#/definitions/baseEntity
      - required:
        - expiresAt
        - method
        - token
        type: object
        properties:
          token:
            type: string
          method:
            type: string
          expiresAt:
            type: string
            format: date-time
          identityId:
            type: string
          caId:
            type: string
            nullable: true
          identity:
            $ref: ../shared/base-entity.yml#/definitions/entityRef
          edgeRouterId:
            type: string
          edgeRouter:
            $ref: ../shared/base-entity.yml#/definitions/entityRef
          transitRouterId:
            type: string
          transitRouter:
            $ref: ../shared/base-entity.yml#/definitions/entityRef
          username:
            type: string
          jwt:
            type: string
    enrollmentCreate:
      required:
      - expiresAt
      - identityId
      - method
      type: object
      properties:
        method:
          type: string
          enum:
          - ott
          - ottca
          - updb
        expiresAt:
          type: string
          format: date-time
        identityId:
          type: string
        caId:
          type: string
          nullable: true
        username:
          type: string
          nullable: true
    enrollmentRefresh:
      required:
      - expiresAt
      type: object
      properties:
        expiresAt:
          type: string
          format: date-time
  responses:
    listEnrollments:
      description: A list of enrollments
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listEnrollmentsEnvelope'
    detailEnrollment:
      description: A singular enrollment resource
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailEnrollmentEnvelope'
x-original-swagger-version: null
