openapi: 3.0.1
servers:
- url: /
paths:
  external-jwt-signers:
    get:
      tags:
      - External JWT Signer
      summary: List External JWT Signers
      description: Retrieves a list of external JWT signers for authentication
      operationId: listExternalJwtSigners
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      responses:
        "200":
          $ref: '#/components/responses/listExternalJwtSigners'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    post:
      tags:
      - External JWT Signer
      summary: Creates an External JWT Signer
      description: Creates an External JWT Signer. Requires admin access.
      operationId: createExternalJwtSigner
      requestBody:
        description: An External JWT Signer to create
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/externalJwtSignerCreate'
        required: true
      responses:
        "201":
          $ref: ../shared/standard-responses.yml#/responses/createResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: externalJwtSigner
  external-jwt-signers-id:
    get:
      tags:
      - External JWT Signer
      summary: Retrieves a single External JWT Signer
      description: Retrieves a single External JWT Signer by id. Requires admin access.
      operationId: detailExternalJwtSigner
      responses:
        "200":
          $ref: '#/components/responses/detailExternalJwtSigner'
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    put:
      tags:
      - External JWT Signer
      summary: Update all fields on an External JWT Signer
      description: Update all fields on an External JWT Signer by id. Requires admin
        access.
      operationId: updateExternalJwtSigner
      requestBody:
        description: An External JWT Signer update object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/externalJwtSignerUpdate'
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/updateResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: externalJwtSigner
    delete:
      tags:
      - External JWT Signer
      summary: Delete an External JWT Signer
      description: |
        Delete an External JWT Signer by id. Requires admin access.
      operationId: deleteExternalJwtSigner
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/deleteResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    patch:
      tags:
      - External JWT Signer
      summary: Update the supplied fields on an External JWT Signer
      description: Update only the supplied fields on an External JWT Signer by id.
        Requires admin access.
      operationId: patchExternalJwtSigner
      requestBody:
        description: An External JWT Signer patch object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/externalJwtSignerPatch'
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/patchResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: externalJwtSigner
    parameters:
    - $ref: ../shared/parameters.yml#/id
components:
  schemas:
    listExternalJwtSignersEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/externalJwtSignerList'
    detailExternalJwtSignerEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/externalJwtSignerDetail'
    externalJwtSignerList:
      type: array
      description: An array of External JWT Signers resources
      items:
        $ref: '#/components/schemas/externalJwtSignerDetail'
    externalJwtSignerDetail:
      description: A External JWT Signer resource
      allOf:
      - $ref: ../shared/base-entity.yml#/definitions/baseEntity
      - required:
        - audience
        - certPem
        - claimsProperty
        - clientId
        - commonName
        - enabled
        - externalAuthUrl
        - fingerprint
        - issuer
        - jwksEndpoint
        - kid
        - name
        - notAfter
        - notBefore
        - scopes
        - useExternalId
        type: object
        properties:
          name:
            type: string
            example: MyApps Signer
          certPem:
            type: string
            nullable: true
          jwksEndpoint:
            type: string
            format: uri
            nullable: true
          enabled:
            type: boolean
          fingerprint:
            type: string
          commonName:
            type: string
          notAfter:
            type: string
            format: date-time
          notBefore:
            type: string
            format: date-time
          externalAuthUrl:
            type: string
            format: url
          claimsProperty:
            type: string
          useExternalId:
            type: boolean
          kid:
            type: string
          issuer:
            type: string
          audience:
            type: string
          clientId:
            type: string
          scopes:
            type: array
            items:
              type: string
    externalJwtSignerCreate:
      required:
      - audience
      - enabled
      - issuer
      - name
      type: object
      properties:
        name:
          type: string
          example: MyApps Signer
        certPem:
          type: string
          nullable: true
        jwksEndpoint:
          type: string
          format: uri
          nullable: true
        enabled:
          type: boolean
        externalAuthUrl:
          type: string
          format: url
          nullable: true
        kid:
          type: string
          nullable: true
        claimsProperty:
          type: string
          nullable: true
        useExternalId:
          type: boolean
          nullable: true
        issuer:
          type: string
        audience:
          type: string
          nullable: true
        clientId:
          type: string
          nullable: true
        scopes:
          type: array
          nullable: true
          items:
            type: string
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
      description: A create Certificate Authority (CA) object
    externalJwtSignerUpdate:
      required:
      - audience
      - enabled
      - issuer
      - name
      type: object
      properties:
        name:
          type: string
          example: MyApps Signer
        certPem:
          type: string
          nullable: true
        jwksEndpoint:
          type: string
          format: uri
          nullable: true
        enabled:
          type: boolean
        externalAuthUrl:
          type: string
          format: url
          nullable: true
        kid:
          type: string
          nullable: true
        claimsProperty:
          type: string
          nullable: true
        useExternalId:
          type: boolean
          nullable: true
        issuer:
          type: string
        audience:
          type: string
          nullable: true
        clientId:
          type: string
          nullable: true
        scopes:
          type: array
          nullable: true
          items:
            type: string
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
    externalJwtSignerPatch:
      type: object
      properties:
        name:
          type: string
          nullable: true
          example: MyApps Signer
        certPem:
          type: string
          nullable: true
        jwksEndpoint:
          type: string
          format: uri
          nullable: true
        enabled:
          type: boolean
          nullable: true
        kid:
          type: string
          nullable: true
        externalAuthUrl:
          type: string
          format: url
          nullable: true
        claimsProperty:
          type: string
          nullable: true
        useExternalId:
          type: boolean
          nullable: true
        issuer:
          type: string
          nullable: true
        audience:
          type: string
          nullable: true
        clientId:
          type: string
          nullable: true
        scopes:
          type: array
          items:
            type: string
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
  responses:
    listExternalJwtSigners:
      description: A list of External JWT Signers
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listExternalJwtSignersEnvelope'
    detailExternalJwtSigner:
      description: A singular External JWT Signer resource
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailExternalJwtSignerEnvelope'
x-original-swagger-version: null
