openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    failedServiceRequestEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/failedServiceRequestList'
    failedServiceRequestList:
      type: array
      items:
        $ref: '#/components/schemas/failedServiceRequest'
    failedServiceRequest:
      type: object
      properties:
        apiSessionId:
          type: string
        when:
          type: string
          format: date-time
        serviceId:
          type: string
        serviceName:
          type: string
        sessionType:
          $ref: ../shared/base-entity.yml#/definitions/dialBind
        policyFailures:
          type: array
          items:
            $ref: '#/components/schemas/policyFailure'
    policyFailure:
      type: object
      properties:
        policyId:
          type: string
        policyName:
          type: string
        checks:
          type: array
          items:
            $ref: '#/components/schemas/postureCheckFailure'
    postureCheckFailure:
      required:
      - postureCheckId
      - postureCheckName
      - postureCheckType
      type: object
      properties:
        postureCheckId:
          type: string
        postureCheckName:
          type: string
        postureCheckType:
          type: string
      discriminator:
        propertyName: postureCheckType
    postureCheckFailureMacAddress:
      allOf:
      - $ref: '#/components/schemas/postureCheckFailure'
      - required:
        - actualValue
        - expectedValue
        type: object
        properties:
          actualValue:
            type: array
            items:
              type: string
          expectedValue:
            type: array
            items:
              type: string
      x-class: MAC
    postureCheckFailureDomain:
      allOf:
      - $ref: '#/components/schemas/postureCheckFailure'
      - required:
        - actualValue
        - expectedValue
        type: object
        properties:
          actualValue:
            type: string
          expectedValue:
            type: array
            items:
              type: string
      x-class: DOMAIN
    postureCheckFailureOperatingSystemActual:
      required:
      - type
      - version
      type: object
      properties:
        type:
          type: string
        version:
          type: string
    postureCheckFailureOperatingSystem:
      allOf:
      - $ref: '#/components/schemas/postureCheckFailure'
      - required:
        - actualValue
        - expectedValue
        type: object
        properties:
          actualValue:
            $ref: '#/components/schemas/postureCheckFailureOperatingSystemActual'
          expectedValue:
            minItems: 1
            type: array
            items:
              $ref: posture-checks.yml#/definitions/operatingSystem
      x-class: OS
    postureCheckFailureProcessActual:
      required:
      - hash
      - isRunning
      - signerFingerprints
      type: object
      properties:
        path:
          type: string
        isRunning:
          type: boolean
        hash:
          type: string
        signerFingerprints:
          type: array
          items:
            type: string
        osType:
          $ref: ../shared/posture-checks.yml#/definitions/osType
    postureCheckFailureProcess:
      allOf:
      - $ref: '#/components/schemas/postureCheckFailure'
      - required:
        - actualValue
        - expectedValue
        type: object
        properties:
          actualValue:
            $ref: '#/components/schemas/postureCheckFailureProcessActual'
          expectedValue:
            $ref: posture-checks.yml#/definitions/process
      x-class: PROCESS
    postureCheckFailureProcessMulti:
      allOf:
      - $ref: '#/components/schemas/postureCheckFailure'
      - required:
        - actualValue
        - expectedValue
        - semantic
        type: object
        properties:
          semantic:
            $ref: ../shared/base-entity.yml#/definitions/semantic
          actualValue:
            type: array
            items:
              $ref: '#/components/schemas/postureCheckFailureProcessActual'
          expectedValue:
            type: array
            items:
              $ref: posture-checks.yml#/definitions/processMulti
      x-class: PROCESS_MULTI
    postureCheckFailureMfa:
      allOf:
      - $ref: '#/components/schemas/postureCheckFailure'
      - required:
        - actualValue
        - criteria
        - expectedValue
        type: object
        properties:
          actualValue:
            $ref: '#/components/schemas/postureChecksFailureMfaValues'
          expectedValue:
            $ref: '#/components/schemas/postureChecksFailureMfaValues'
          criteria:
            $ref: '#/components/schemas/postureChecksFailureMfaCriteria'
      x-class: MFA
    postureChecksFailureMfaValues:
      type: object
      properties:
        passedMfa:
          type: boolean
          x-omitempty: false
        passedOnWake:
          type: boolean
          x-omitempty: false
        passedOnUnlock:
          type: boolean
          x-omitempty: false
        timedOut:
          type: boolean
          x-omitempty: false
    postureChecksFailureMfaCriteria:
      required:
      - passedMfaAt
      - timeoutRemainingSeconds
      - timeoutSeconds
      - unlockedAt
      - wokenAt
      type: object
      properties:
        passedMfaAt:
          type: string
          format: date-time
        wokenAt:
          type: string
          format: date-time
        unlockedAt:
          type: string
          format: date-time
        timeoutSeconds:
          type: integer
        timeoutRemainingSeconds:
          type: integer
x-original-swagger-version: null
