openapi: 3.0.1
servers:
- url: /
paths:
  identity-types:
    get:
      tags:
      - Identity
      summary: List available identity types
      description: |
        Retrieves a list of identity types; supports filtering, sorting, and pagination. Requires admin access.
      operationId: listIdentityTypes
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      responses:
        "200":
          $ref: '#/components/responses/listIdentityTypes'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
  identity-types-id:
    get:
      tags:
      - Identity
      summary: Retrieves a identity type
      description: Retrieves a single identity type by id. Requires admin access.
      operationId: detailIdentityType
      responses:
        "200":
          $ref: '#/components/responses/detailIdentityType'
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
components:
  schemas:
    identityType:
      type: string
      enum:
      - User
      - Device
      - Service
      - Router
      - Default
    listIdentityTypesEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/identityTypeList'
    detailIdentityTypeEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/identityTypeDetail'
    identityTypeList:
      type: array
      items:
        $ref: '#/components/schemas/identityTypeDetail'
    identityTypeDetail:
      allOf:
      - $ref: ../shared/base-entity.yml#/definitions/baseEntity
      - type: object
        properties:
          name:
            type: string
  responses:
    listIdentityTypes:
      description: A list of identity types
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listIdentityTypesEnvelope'
    detailIdentityType:
      description: A single identity type
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailIdentityTypeEnvelope'
x-original-swagger-version: null
