openapi: 3.0.1
servers:
- url: /
paths:
  posture-checks:
    get:
      tags:
      - Posture Checks
      summary: List a subset of posture checks
      description: |
        Retrieves a list of posture checks
      operationId: listPostureChecks
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      - $ref: ../shared/parameters.yml#/roleFilter
      - $ref: ../shared/parameters.yml#/roleSemantic
      responses:
        "200":
          $ref: '#/components/responses/listPostureChecks'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    post:
      tags:
      - Posture Checks
      summary: Creates a Posture Checks
      description: Creates a Posture Checks
      operationId: createPostureCheck
      requestBody:
        description: A Posture Check to create
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/postureCheckCreate'
        required: true
      responses:
        "201":
          $ref: ../shared/standard-responses.yml#/responses/createResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: postureCheck
  posture-checks-id:
    get:
      tags:
      - Posture Checks
      summary: Retrieves a single Posture Checks
      description: Retrieves a single Posture Checks by id
      operationId: detailPostureCheck
      responses:
        "200":
          $ref: '#/components/responses/detailPostureCheck'
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    put:
      tags:
      - Posture Checks
      summary: Update all fields on a Posture Checks
      description: Update all fields on a Posture Checks by id
      operationId: updatePostureCheck
      requestBody:
        description: A Posture Check update object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/postureCheckUpdate'
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/updateResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: postureCheck
    delete:
      tags:
      - Posture Checks
      summary: Deletes an Posture Checks
      description: Deletes and Posture Checks by id
      operationId: deletePostureCheck
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/deleteResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "403":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    patch:
      tags:
      - Posture Checks
      summary: Update the supplied fields on a Posture Checks
      description: Update only the supplied fields on a Posture Checks by id
      operationId: patchPostureCheck
      requestBody:
        description: A Posture Check patch object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/postureCheckPatch'
        required: true
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/patchResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
      x-codegen-request-body-name: postureCheck
    parameters:
    - $ref: ../shared/parameters.yml#/id
components:
  schemas:
    listPostureCheckEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          type: array
          items:
            $ref: '#/components/schemas/postureCheckDetail'
    detailPostureCheckEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/postureCheckDetail'
    operatingSystem:
      required:
      - type
      - versions
      type: object
      properties:
        type:
          $ref: ../shared/posture-checks.yml#/definitions/osType
        versions:
          type: array
          items:
            type: string
    postureCheckDetail:
      required:
      - _links
      - createdAt
      - id
      - name
      - roleAttributes
      - tags
      - typeId
      - updatedAt
      - version
      type: object
      properties:
        name:
          type: string
        typeId:
          type: string
        version:
          type: integer
        roleAttributes:
          $ref: ../shared/base-entity.yml#/definitions/attributes
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        _links:
          $ref: ../shared/base-entity.yml#/definitions/links
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
      discriminator:
        propertyName: typeId
    postureCheckCreate:
      required:
      - name
      - typeId
      type: object
      properties:
        name:
          type: string
        typeId:
          $ref: ../shared/posture-checks.yml#/definitions/postureCheckType
        roleAttributes:
          $ref: ../shared/base-entity.yml#/definitions/attributes
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
      discriminator:
        propertyName: typeId
    postureCheckUpdate:
      required:
      - name
      type: object
      properties:
        name:
          type: string
        typeId:
          $ref: ../shared/posture-checks.yml#/definitions/postureCheckType
        roleAttributes:
          $ref: ../shared/base-entity.yml#/definitions/attributes
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
      discriminator:
        propertyName: typeId
    postureCheckPatch:
      required:
      - typeId
      type: object
      properties:
        name:
          type: string
        typeId:
          $ref: ../shared/posture-checks.yml#/definitions/postureCheckType
        roleAttributes:
          $ref: ../shared/base-entity.yml#/definitions/attributes
        tags:
          $ref: ../shared/base-entity.yml#/definitions/tags
      discriminator:
        propertyName: typeId
    postureCheckOperatingSystemDetail:
      allOf:
      - $ref: '#/components/schemas/postureCheckDetail'
      - required:
        - operatingSystems
        type: object
        properties:
          operatingSystems:
            type: array
            items:
              $ref: '#/components/schemas/operatingSystem'
      x-class: OS
    postureCheckOperatingSystemCreate:
      allOf:
      - $ref: '#/components/schemas/postureCheckCreate'
      - required:
        - operatingSystems
        type: object
        properties:
          operatingSystems:
            minItems: 1
            type: array
            items:
              $ref: '#/components/schemas/operatingSystem'
      x-class: OS
    postureCheckOperatingSystemUpdate:
      allOf:
      - $ref: '#/components/schemas/postureCheckUpdate'
      - required:
        - operatingSystems
        type: object
        properties:
          operatingSystems:
            minItems: 1
            type: array
            items:
              $ref: '#/components/schemas/operatingSystem'
      x-class: OS
    postureCheckOperatingSystemPatch:
      allOf:
      - $ref: '#/components/schemas/postureCheckPatch'
      - type: object
        properties:
          operatingSystems:
            minItems: 1
            type: array
            items:
              $ref: '#/components/schemas/operatingSystem'
      x-class: OS
    postureCheckDomainDetail:
      allOf:
      - $ref: '#/components/schemas/postureCheckDetail'
      - required:
        - domains
        type: object
        properties:
          domains:
            minItems: 1
            type: array
            items:
              type: string
      x-class: DOMAIN
    postureCheckDomainCreate:
      allOf:
      - $ref: '#/components/schemas/postureCheckCreate'
      - required:
        - domains
        type: object
        properties:
          domains:
            minItems: 1
            type: array
            items:
              type: string
      x-class: DOMAIN
    postureCheckDomainUpdate:
      allOf:
      - $ref: '#/components/schemas/postureCheckUpdate'
      - required:
        - domains
        type: object
        properties:
          domains:
            minItems: 1
            type: array
            items:
              type: string
      x-class: DOMAIN
    postureCheckDomainPatch:
      allOf:
      - $ref: '#/components/schemas/postureCheckPatch'
      - type: object
        properties:
          domains:
            minItems: 1
            type: array
            items:
              type: string
      x-class: DOMAIN
    postureCheckMacAddressDetail:
      allOf:
      - $ref: '#/components/schemas/postureCheckDetail'
      - required:
        - macAddresses
        type: object
        properties:
          macAddresses:
            minItems: 1
            type: array
            items:
              type: string
      x-class: MAC
    postureCheckMacAddressCreate:
      allOf:
      - $ref: '#/components/schemas/postureCheckCreate'
      - required:
        - macAddresses
        type: object
        properties:
          macAddresses:
            minItems: 1
            type: array
            items:
              type: string
      x-class: MAC
    postureCheckMacAddressUpdate:
      allOf:
      - $ref: '#/components/schemas/postureCheckUpdate'
      - required:
        - macAddresses
        type: object
        properties:
          macAddresses:
            minItems: 1
            type: array
            items:
              type: string
      x-class: MAC
    postureCheckMacAddressPatch:
      allOf:
      - $ref: '#/components/schemas/postureCheckPatch'
      - type: object
        properties:
          macAddresses:
            minItems: 1
            type: array
            items:
              type: string
      x-class: MAC
    process:
      required:
      - osType
      - path
      type: object
      properties:
        osType:
          $ref: ../shared/posture-checks.yml#/definitions/osType
        path:
          type: string
        hashes:
          type: array
          items:
            type: string
        signerFingerprint:
          type: string
    postureCheckProcessDetail:
      allOf:
      - $ref: '#/components/schemas/postureCheckDetail'
      - required:
        - process
        type: object
        properties:
          process:
            $ref: '#/components/schemas/process'
      x-class: PROCESS
    postureCheckProcessCreate:
      allOf:
      - $ref: '#/components/schemas/postureCheckCreate'
      - required:
        - process
        type: object
        properties:
          process:
            $ref: '#/components/schemas/process'
      x-class: PROCESS
    postureCheckProcessUpdate:
      allOf:
      - $ref: '#/components/schemas/postureCheckUpdate'
      - required:
        - process
        type: object
        properties:
          process:
            $ref: '#/components/schemas/process'
      x-class: PROCESS
    postureCheckProcessPatch:
      allOf:
      - $ref: '#/components/schemas/postureCheckPatch'
      - type: object
        properties:
          process:
            $ref: '#/components/schemas/process'
      x-class: PROCESS
    processMulti:
      required:
      - osType
      - path
      type: object
      properties:
        osType:
          $ref: ../shared/posture-checks.yml#/definitions/osType
        path:
          type: string
        hashes:
          type: array
          items:
            type: string
        signerFingerprints:
          type: array
          items:
            type: string
    postureCheckProcessMultiDetail:
      allOf:
      - $ref: '#/components/schemas/postureCheckDetail'
      - required:
        - processes
        - semantic
        type: object
        properties:
          semantic:
            $ref: ../shared/base-entity.yml#/definitions/semantic
          processes:
            minItems: 1
            type: array
            items:
              $ref: '#/components/schemas/processMulti'
      x-class: PROCESS_MULTI
    postureCheckProcessMultiCreate:
      allOf:
      - $ref: '#/components/schemas/postureCheckCreate'
      - required:
        - processes
        - semantic
        type: object
        properties:
          semantic:
            $ref: ../shared/base-entity.yml#/definitions/semantic
          processes:
            minItems: 1
            type: array
            items:
              $ref: '#/components/schemas/processMulti'
      x-class: PROCESS_MULTI
    postureCheckProcessMultiUpdate:
      allOf:
      - $ref: '#/components/schemas/postureCheckUpdate'
      - required:
        - processes
        - semantic
        type: object
        properties:
          semantic:
            $ref: ../shared/base-entity.yml#/definitions/semantic
          processes:
            minItems: 1
            type: array
            items:
              $ref: '#/components/schemas/processMulti'
      x-class: PROCESS_MULTI
    postureCheckProcessMultiPatch:
      allOf:
      - $ref: '#/components/schemas/postureCheckPatch'
      - type: object
        properties:
          semantic:
            $ref: ../shared/base-entity.yml#/definitions/semantic
          processes:
            minItems: 1
            type: array
            items:
              $ref: '#/components/schemas/processMulti'
      x-class: PROCESS_MULTI
    postureCheckMfaProperties:
      type: object
      properties:
        timeoutSeconds:
          type: integer
        promptOnWake:
          type: boolean
        promptOnUnlock:
          type: boolean
        ignoreLegacyEndpoints:
          type: boolean
    postureCheckMfaPropertiesPatch:
      type: object
      properties:
        timeoutSeconds:
          type: integer
          nullable: true
        promptOnWake:
          type: boolean
          nullable: true
        promptOnUnlock:
          type: boolean
          nullable: true
        ignoreLegacyEndpoints:
          type: boolean
          nullable: true
    postureCheckMfaDetail:
      allOf:
      - $ref: '#/components/schemas/postureCheckDetail'
      - $ref: '#/components/schemas/postureCheckMfaProperties'
      x-class: MFA
    postureCheckMfaCreate:
      allOf:
      - $ref: '#/components/schemas/postureCheckCreate'
      - $ref: '#/components/schemas/postureCheckMfaProperties'
      x-class: MFA
    postureCheckMfaUpdate:
      allOf:
      - $ref: '#/components/schemas/postureCheckUpdate'
      - $ref: '#/components/schemas/postureCheckMfaProperties'
      x-class: MFA
    postureCheckMfaPatch:
      allOf:
      - $ref: '#/components/schemas/postureCheckPatch'
      - $ref: '#/components/schemas/postureCheckMfaPropertiesPatch'
      x-class: MFA
  responses:
    listPostureChecks:
      description: A list of posture checks
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listPostureCheckEnvelope'
    detailPostureCheck:
      description: Retrieves a singular posture check by id
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailPostureCheckEnvelope'
x-original-swagger-version: null
