openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    postureDataEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/postureData'
    postureData:
      required:
      - apiSessionPostureData
      - domain
      - mac
      - os
      - processes
      type: object
      properties:
        mac:
          $ref: '#/components/schemas/postureDataMac'
        domain:
          $ref: '#/components/schemas/postureDataDomain'
        os:
          $ref: '#/components/schemas/postureDataOs'
        processes:
          type: array
          items:
            $ref: '#/components/schemas/postureDataProcess'
        apiSessionPostureData:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/apiSessionPostureData'
    postureDataBase:
      required:
      - lastUpdatedAt
      - postureCheckId
      - timedOut
      type: object
      properties:
        postureCheckId:
          type: string
        timedOut:
          type: boolean
        lastUpdatedAt:
          type: string
          format: date-time
    postureDataMac:
      allOf:
      - $ref: '#/components/schemas/postureDataBase'
      - required:
        - addresses
        type: object
        properties:
          addresses:
            type: array
            items:
              type: string
    postureDataDomain:
      allOf:
      - $ref: '#/components/schemas/postureDataBase'
      - required:
        - domain
        type: object
        properties:
          domain:
            type: string
    postureDataOs:
      allOf:
      - $ref: '#/components/schemas/postureDataBase'
      - required:
        - build
        - type
        - version
        type: object
        properties:
          type:
            type: string
          version:
            type: string
          build:
            type: string
    postureDataProcess:
      allOf:
      - $ref: '#/components/schemas/postureDataBase'
      - type: object
        properties:
          isRunning:
            type: boolean
          binaryHash:
            type: string
          signerFingerprints:
            type: array
            items:
              type: string
    postureDataMfa:
      required:
      - apiSessionId
      - passedAt
      - passedMfa
      - passedOnUnlock
      - passedOnWake
      type: object
      properties:
        apiSessionId:
          type: string
        passedAt:
          type: string
          format: date-time
          x-omitempty: false
        passedMfa:
          type: boolean
          x-omitempty: false
        passedOnWake:
          type: boolean
          x-omitempty: false
        passedOnUnlock:
          type: boolean
          x-omitempty: false
    postureDataEndpointState:
      required:
      - unlockedAt
      - wokenAt
      type: object
      properties:
        wokenAt:
          type: string
          format: date-time
        unlockedAt:
          type: string
          format: date-time
    apiSessionPostureData:
      required:
      - mfa
      type: object
      properties:
        mfa:
          $ref: '#/components/schemas/postureDataMfa'
        endpointState:
          $ref: '#/components/schemas/postureDataEndpointState'
        sdkInfo:
          $ref: ../shared/authenticate.yml#/definitions/sdkInfo
x-original-swagger-version: null
