openapi: 3.0.1
servers:
- url: /
paths:
  sessions:
    get:
      tags:
      - Session
      summary: List sessions
      description: |
        Retrieves a list of active sessions resources; supports filtering, sorting, and pagination. Requires admin access.

        Sessions are tied to an API session and are moved when an API session times out or logs out. Active sessions
        (i.e. Ziti SDK connected to an edge router) will keep the session and API session marked as active.
      operationId: listSessions
      parameters:
      - $ref: ../shared/parameters.yml#/limit
      - $ref: ../shared/parameters.yml#/offset
      - $ref: ../shared/parameters.yml#/filter
      responses:
        "200":
          $ref: '#/components/responses/listSessionsManagement'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
  sessions-id:
    get:
      tags:
      - Session
      summary: Retrieves a single session
      description: Retrieves a single session by id. Requires admin access.
      operationId: detailSession
      responses:
        "200":
          $ref: '#/components/responses/detailSessionManagement'
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    delete:
      tags:
      - Session
      summary: Delete a session
      description: Delete a session by id. Requires admin access.
      operationId: deleteSession
      responses:
        "200":
          $ref: ../shared/standard-responses.yml#/responses/deleteResponse
        "400":
          $ref: ../shared/standard-responses.yml#/responses/badRequestResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "409":
          $ref: ../shared/standard-responses.yml#/responses/cannotDeleteReferencedResourceResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
  sessions-id-route-path:
    get:
      tags:
      - Session
      summary: Retrieves a single session's router path
      description: Retrieves a single session's route path by id. Requires admin access.
      operationId: detailSessionRoutePath
      responses:
        "200":
          $ref: '#/components/responses/detailSessionRoutePath'
        "404":
          $ref: ../shared/standard-responses.yml#/responses/notFoundResponse
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    parameters:
    - $ref: ../shared/parameters.yml#/id
components:
  schemas:
    detailSessionRoutePathEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/sessionRoutePathDetail'
    sessionRoutePathDetail:
      type: object
      properties:
        routePath:
          type: array
          items:
            type: string
    listSessionsManagementEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/sessionManagementList'
    detailSessionManagementEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/sessionManagementDetail'
    sessionManagementList:
      type: array
      items:
        $ref: '#/components/schemas/sessionManagementDetail'
    sessionManagementDetail:
      allOf:
      - $ref: ../shared/sessions.yml#/definitions/sessionDetail
      - type: object
        properties:
          servicePolicies:
            type: array
            items:
              $ref: ../shared/base-entity.yml#/definitions/entityRef
  responses:
    detailSessionRoutePath:
      description: A single session's route path
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailSessionRoutePathEnvelope'
    listSessionsManagement:
      description: A list of sessions
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listSessionsManagementEnvelope'
    detailSessionManagement:
      description: A single session
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailSessionManagementEnvelope'
x-original-swagger-version: null
