openapi: 3.0.1
servers:
- url: /
paths:
  summary:
    get:
      tags:
      - Informational
      summary: Returns a list of accessible resource counts
      description: This endpoint is usefull for UIs that wish to display UI elements
        with counts.
      operationId: listSummary
      responses:
        "200":
          $ref: '#/components/responses/listSummaryCounts'
        "401":
          $ref: ../shared/standard-responses.yml#/responses/unauthorizedResponse
        "429":
          $ref: ../shared/standard-responses.yml#/responses/rateLimitedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
components:
  schemas:
    listSummaryCountsEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/listSummaryCounts'
    listSummaryCounts:
      type: object
      additionalProperties:
        type: integer
  responses:
    listSummaryCounts:
      description: Entity counts scopped to the current identitie's access
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listSummaryCountsEnvelope'
x-original-swagger-version: null
