openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    listAPISessionsEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/apiSessionList'
    detailApiSessionEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/apiSessionDetail'
    apiSessionList:
      type: array
      items:
        $ref: '#/components/schemas/apiSessionDetail'
    apiSessionDetail:
      description: An API Session object
      allOf:
      - $ref: base-entity.yml#/definitions/baseEntity
      - required:
        - authQueries
        - authenticatorId
        - configTypes
        - identity
        - identityId
        - ipAddress
        - isCertExtendable
        - isMfaComplete
        - isMfaRequired
        - token
        type: object
        properties:
          token:
            type: string
          identity:
            $ref: base-entity.yml#/definitions/entityRef
          identityId:
            type: string
          ipAddress:
            type: string
          configTypes:
            type: array
            items:
              type: string
          authQueries:
            $ref: auth-query.yml#/definitions/authQueryList
          isMfaRequired:
            type: boolean
          isMfaComplete:
            type: boolean
          lastActivityAt:
            type: string
            format: date-time
          cachedLastActivityAt:
            type: string
            format: date-time
          authenticatorId:
            type: string
          isCertExtendable:
            type: boolean
x-original-swagger-version: null
