openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    listAuthenticatorsEnvelope:
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/authenticatorList'
    detailAuthenticatorEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/authenticatorDetail'
    authenticatorCreate:
      required:
      - identityId
      - method
      type: object
      properties:
        method:
          type: string
          description: The type of authenticator to create; which will dictate which
            properties on this object are required.
        identityId:
          type: string
          description: The id of an existing identity that will be assigned this authenticator
        tags:
          $ref: base-entity.yml#/definitions/tags
        username:
          type: string
          description: The username that the identity will login with. Used only for
            method='updb'
        password:
          type: string
          description: The password the identity will login with. Used only for method='updb'
        certPem:
          type: string
          description: The client certificate the identity will login with. Used only
            for method='cert'
      description: Creates an authenticator for a specific identity which can be used
        for API authentication
    authenticatorList:
      type: array
      description: An array of authenticator resources
      items:
        $ref: '#/components/schemas/authenticatorDetail'
    authenticatorDetail:
      description: A singular authenticator resource
      allOf:
      - $ref: base-entity.yml#/definitions/baseEntity
      - required:
        - identity
        - identityId
        - method
        type: object
        properties:
          method:
            type: string
          identityId:
            type: string
          identity:
            $ref: base-entity.yml#/definitions/entityRef
          certPem:
            type: string
          fingerprint:
            type: string
          username:
            type: string
          isIssuedByNetwork:
            type: boolean
    authenticatorUpdate:
      required:
      - password
      - username
      type: object
      properties:
        username:
          $ref: authenticate.yml#/definitions/username
        password:
          $ref: authenticate.yml#/definitions/password
        tags:
          $ref: base-entity.yml#/definitions/tags
      description: All of the fields on an authenticator that will be updated
    authenticatorPatch:
      type: object
      properties:
        username:
          $ref: authenticate.yml#/definitions/username-nullable
        password:
          $ref: authenticate.yml#/definitions/password-nullable
        tags:
          $ref: base-entity.yml#/definitions/tags
      description: All of the fields on an authenticator that may be updated
    authenticatorUpdateWithCurrent:
      description: All of the fields on an authenticator that will be updated
      allOf:
      - $ref: '#/components/schemas/authenticatorUpdate'
      - required:
        - currentPassword
        type: object
        properties:
          currentPassword:
            $ref: authenticate.yml#/definitions/password
    authenticatorPatchWithCurrent:
      description: All of the fields on an authenticator that may be updated
      allOf:
      - $ref: '#/components/schemas/authenticatorPatch'
      - required:
        - currentPassword
        type: object
        properties:
          currentPassword:
            $ref: authenticate.yml#/definitions/password
  responses:
    listAuthenticators:
      description: A list of authenticators
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listAuthenticatorsEnvelope'
    detailAuthenticator:
      description: A singular authenticator resource
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailAuthenticatorEnvelope'
x-original-swagger-version: null
