openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    authQueryList:
      type: array
      items:
        $ref: '#/components/schemas/authQueryDetail'
    authQueryDetail:
      required:
      - provider
      type: object
      properties:
        typeId:
          type: string
        provider:
          $ref: current-identity-mfa.yml#/definitions/mfaProviders
        httpMethod:
          type: string
        httpUrl:
          type: string
        minLength:
          type: integer
        maxLength:
          type: integer
        format:
          $ref: current-identity-mfa.yml#/definitions/mfaFormats
x-original-swagger-version: null
