openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    baseEntity:
      required:
      - _links
      - createdAt
      - id
      - updatedAt
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        _links:
          $ref: '#/components/schemas/links'
        tags:
          $ref: '#/components/schemas/tags'
      description: Fields shared by all Edge API entities
    link:
      required:
      - href
      type: object
      properties:
        href:
          type: string
          format: uri
        method:
          type: string
        comment:
          type: string
      description: A link to another resource
    links:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/link'
      description: A map of named links
      x-omitempty: false
    entityRef:
      type: object
      properties:
        entity:
          type: string
        id:
          type: string
        name:
          type: string
        _links:
          $ref: '#/components/schemas/links'
      description: A reference to another resource and links to interact with it
    tags:
      description: "A map of user defined fields and values. The values are limited\
        \ to the following types/values: null, string, boolean"
      allOf:
      - $ref: '#/components/schemas/subTags'
    subTags:
      type: object
      additionalProperties:
        type: object
        properties: {}
    attributes:
      type: array
      description: A set of strings used to loosly couple this resource to policies
      nullable: true
      items:
        type: string
      x-omitempty: true
      x-nullable: true
    roles:
      type: array
      items:
        type: string
      x-omitempty: false
    namedRole:
      type: object
      properties:
        role:
          type: string
        name:
          type: string
    namedRoles:
      type: array
      items:
        $ref: '#/components/schemas/namedRole'
      x-omitempty: false
    semantic:
      type: string
      enum:
      - AllOf
      - AnyOf
    dialBind:
      type: string
      enum:
      - Dial
      - Bind
      - Invalid
    dialBindArray:
      type: array
      items:
        $ref: '#/components/schemas/dialBind'
x-original-swagger-version: null
