openapi: 3.0.1
servers:
- url: /
paths:
  current-api-session:
    get:
      tags:
      - Current API Session
      summary: Return the current API session
      description: Retrieves the API session that was used to issue the current request
      operationId: getCurrentAPISession
      responses:
        "200":
          $ref: '#/components/responses/detailCurrentAPISession'
        "401":
          $ref: standard-responses.yml#/responses/unauthorizedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
    delete:
      tags:
      - Current API Session
      summary: Logout
      description: Terminates the current API session
      responses:
        "200":
          $ref: standard-responses.yml#/responses/emptyResponse
        "401":
          $ref: standard-responses.yml#/responses/unauthorizedResponse
      security:
      - ztSession: []
      - oauth2:
        - openid
components:
  schemas:
    detailApiSessionEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: api-sessions.yml#/definitions/apiSessionDetail
    currentApiSessionDetailEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/currentApiSessionDetail'
    currentApiSessionDetail:
      description: An API Session object for the current API session
      allOf:
      - $ref: api-sessions.yml#/definitions/apiSessionDetail
      - required:
        - expirationSeconds
        - expiresAt
        type: object
        properties:
          expiresAt:
            type: string
            format: date-time
          expirationSeconds:
            type: integer
  responses:
    detailCurrentAPISession:
      description: The API session associated with the session used to issue the request
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/currentApiSessionDetailEnvelope'
        default:
          example:
            meta: {}
            data:
              id: 27343114-b44f-406e-9981-f3c4f2f28d54
              createdAt: 2020-03-09T19:03:49.1883693Z
              updatedAt: 2020-03-09T19:04:21.5600897Z
              _links:
                self:
                  href: ./current-api-session
              tags:
              - userField1: 123
              - userField2: asdf
              token: 28bb0ed2-0577-4632-ae70-d17106b92871
              identity:
                urlName: identities
                id: 66352d7b-a6b2-4ce9-85bb-9f18e318704d
                name: Default Admin
                _links:
                  self:
                    href: ./identities/66352d7b-a6b2-4ce9-85bb-9f18e318704d
              expiresAt: 2020-03-09T19:34:21.5600897Z
              configTypes: []
x-original-swagger-version: null
