openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    serviceEdgeRouters:
      type: object
      properties:
        edgeRouters:
          type: array
          items:
            $ref: '#/components/schemas/commonEdgeRouterProperties'
    commonEdgeRouterProperties:
      required:
      - cost
      - disabled
      - hostname
      - isOnline
      - name
      - noTraversal
      - supportedProtocols
      - syncStatus
      type: object
      properties:
        hostname:
          type: string
        name:
          type: string
        supportedProtocols:
          type: object
          additionalProperties:
            type: string
        syncStatus:
          type: string
        isOnline:
          type: boolean
        cost:
          maximum: 65535
          minimum: 0
          type: integer
          nullable: true
        noTraversal:
          type: boolean
          nullable: true
        disabled:
          type: boolean
        appData:
          $ref: base-entity.yml#/definitions/tags
x-original-swagger-version: null
