openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    identityList:
      type: array
      description: A list of identities
      items:
        $ref: '#/components/schemas/identityDetail'
    identityDetail:
      description: Detail of a specific identity
      allOf:
      - $ref: base-entity.yml#/definitions/baseEntity
      - required:
        - authPolicy
        - authPolicyId
        - authenticators
        - defaultHostingCost
        - disabled
        - enrollment
        - envInfo
        - externalId
        - hasApiSession
        - hasEdgeRouterConnection
        - isAdmin
        - isDefaultAdmin
        - isMfaEnabled
        - name
        - roleAttributes
        - sdkInfo
        - serviceHostingCosts
        - serviceHostingPrecedences
        - type
        - typeId
        type: object
        properties:
          name:
            type: string
          type:
            $ref: base-entity.yml#/definitions/entityRef
          typeId:
            type: string
          isDefaultAdmin:
            type: boolean
          isAdmin:
            type: boolean
          authenticators:
            $ref: '#/components/schemas/identityAuthenticators'
          enrollment:
            $ref: '#/components/schemas/identityEnrollments'
          envInfo:
            $ref: authenticate.yml#/definitions/envInfo
          sdkInfo:
            $ref: authenticate.yml#/definitions/sdkInfo
          roleAttributes:
            $ref: base-entity.yml#/definitions/attributes
          hasEdgeRouterConnection:
            type: boolean
          hasApiSession:
            type: boolean
          isMfaEnabled:
            type: boolean
          authPolicyId:
            type: string
          authPolicy:
            $ref: base-entity.yml#/definitions/entityRef
          defaultHostingPrecedence:
            $ref: terminators.yml#/definitions/terminatorPrecedence
          defaultHostingCost:
            $ref: terminators.yml#/definitions/terminatorCost
          serviceHostingPrecedences:
            $ref: terminators.yml#/definitions/terminatorPrecedenceMap
          serviceHostingCosts:
            $ref: terminators.yml#/definitions/terminatorCostMap
          appData:
            $ref: base-entity.yml#/definitions/tags
          externalId:
            type: string
            nullable: true
          disabled:
            type: boolean
          disabledAt:
            type: string
            format: date-time
            nullable: true
          disabledUntil:
            type: string
            format: date-time
            nullable: true
    identityAuthenticators:
      type: object
      properties:
        updb:
          type: object
          properties:
            id:
              type: string
            username:
              type: string
        cert:
          type: object
          properties:
            id:
              type: string
            fingerprint:
              type: string
    identityEnrollments:
      type: object
      properties:
        updb:
          type: object
          properties:
            id:
              type: string
            token:
              type: string
            jwt:
              type: string
            expiresAt:
              type: string
              format: date-time
        ott:
          type: object
          properties:
            id:
              type: string
            token:
              type: string
            jwt:
              type: string
            expiresAt:
              type: string
              format: date-time
        ottca:
          type: object
          properties:
            id:
              type: string
            token:
              type: string
            jwt:
              type: string
            caId:
              type: string
            ca:
              $ref: base-entity.yml#/definitions/entityRef
            expiresAt:
              type: string
              format: date-time
x-original-swagger-version: null
