openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    postureQueries:
      required:
      - isPassing
      - policyId
      - postureQueries
      type: object
      properties:
        policyId:
          type: string
        isPassing:
          type: boolean
        policyType:
          $ref: base-entity.yml#/definitions/dialBind
        postureQueries:
          type: array
          items:
            $ref: '#/components/schemas/postureQuery'
    postureQuery:
      allOf:
      - $ref: base-entity.yml#/definitions/baseEntity
      - required:
        - isPassing
        - queryType
        - timeout
        - timeoutRemaining
        type: object
        properties:
          isPassing:
            type: boolean
          timeout:
            type: integer
          timeoutRemaining:
            type: integer
          queryType:
            $ref: posture-checks.yml#/definitions/postureCheckType
          process:
            $ref: '#/components/schemas/postureQueryProcess'
          processes:
            type: array
            items:
              $ref: '#/components/schemas/postureQueryProcess'
    postureQueryProcess:
      type: object
      properties:
        osType:
          $ref: posture-checks.yml#/definitions/osType
        path:
          type: string
x-original-swagger-version: null
