openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    listServicesEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/serviceList'
    detailServiceEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: ../shared/standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/serviceDetail'
    serviceList:
      type: array
      items:
        $ref: '#/components/schemas/serviceDetail'
    serviceDetail:
      allOf:
      - $ref: ../shared/base-entity.yml#/definitions/baseEntity
      - required:
        - config
        - configs
        - encryptionRequired
        - maxIdleTimeMillis
        - name
        - permissions
        - postureQueries
        - roleAttributes
        - terminatorStrategy
        type: object
        properties:
          name:
            type: string
          maxIdleTimeMillis:
            type: integer
          terminatorStrategy:
            type: string
          roleAttributes:
            $ref: ../shared/base-entity.yml#/definitions/attributes
          permissions:
            $ref: ../shared/base-entity.yml#/definitions/dialBindArray
          configs:
            type: array
            items:
              type: string
          config:
            type: object
            additionalProperties:
              type: object
              additionalProperties:
                type: object
                properties: {}
            description: map of config data for this service keyed by the config type
              name. Only configs of the types requested will be returned.
          encryptionRequired:
            type: boolean
            description: "Describes whether connections must support end-to-end encryption\
              \ on both sides of the connection. Read-only property, set at create."
          postureQueries:
            type: array
            items:
              $ref: ../shared/posture-queries.yml#/definitions/postureQueries
  responses:
    listServices:
      description: A list of services
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listServicesEnvelope'
    detailService:
      description: A single service
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailServiceEnvelope'
x-original-swagger-version: null
