openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    listSessionsEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/sessionList'
    detailSessionEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/sessionDetail'
    sessionList:
      type: array
      items:
        $ref: '#/components/schemas/sessionDetail'
    sessionDetail:
      allOf:
      - $ref: base-entity.yml#/definitions/baseEntity
      - required:
        - apiSession
        - apiSessionId
        - edgeRouters
        - identityId
        - service
        - serviceId
        - token
        - type
        type: object
        properties:
          type:
            $ref: base-entity.yml#/definitions/dialBind
          token:
            type: string
          apiSessionId:
            type: string
          apiSession:
            $ref: base-entity.yml#/definitions/entityRef
          serviceId:
            type: string
          service:
            $ref: base-entity.yml#/definitions/entityRef
          edgeRouters:
            type: array
            items:
              $ref: '#/components/schemas/sessionEdgeRouter'
          identityId:
            type: string
    sessionEdgeRouter:
      allOf:
      - $ref: edge-routers.yml#/definitions/commonEdgeRouterProperties
      - required:
        - urls
        type: object
        properties:
          urls:
            type: object
            additionalProperties:
              type: string
  responses:
    listSessions:
      description: A list of sessions
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listSessionsEnvelope'
    detailSession:
      description: A single session
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailSessionEnvelope'
x-original-swagger-version: null
