openapi: 3.0.1
servers:
- url: /
paths:
  specs:
    get:
      tags:
      - Informational
      summary: Returns a list of API specs
      description: Returns a list of spec files embedded within the controller for
        consumption/documentation/code geneartion
      operationId: listSpecs
      responses:
        "200":
          $ref: '#/components/responses/listSpecs'
      security: []
  specs-id:
    get:
      tags:
      - Informational
      summary: Return a single spec resource
      description: Returns single spec resource embedded within the controller for
        consumption/documentation/code geneartion
      operationId: detailSpec
      responses:
        "200":
          $ref: '#/components/responses/detailSpec'
      security: []
    parameters:
    - $ref: parameters.yml#/id
  specs-id-spec:
    get:
      tags:
      - Informational
      summary: Returns the spec's file
      description: "Return the body of the specification (i.e. Swagger, OpenAPI 2.0,\
        \ 3.0, etc)."
      operationId: detailSpecBody
      responses:
        "200":
          $ref: '#/components/responses/detailSpecBody'
      security: []
    parameters:
    - $ref: parameters.yml#/id
components:
  schemas:
    listSpecsEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/specList'
    detailSpecEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/specDetail'
    detailSpecBodyEnvelope:
      required:
      - data
      - meta
      type: object
      properties:
        meta:
          $ref: standard-responses.yml#/definitions/meta
        data:
          $ref: '#/components/schemas/specBodyDetail'
    specList:
      type: array
      items:
        $ref: '#/components/schemas/specDetail'
    specDetail:
      allOf:
      - $ref: base-entity.yml#/definitions/baseEntity
      - required:
        - name
        type: object
        properties:
          name:
            type: string
    specBodyDetail:
      type: string
  responses:
    listSpecs:
      description: A list of specifications
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/listSpecsEnvelope'
    detailSpec:
      description: A single specification
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailSpecEnvelope'
    detailSpecBody:
      description: Returns the document that represents the specification
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/detailSpecBodyEnvelope'
x-original-swagger-version: null
