openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    pagination:
      required:
      - limit
      - offset
      - totalCount
      type: object
      properties:
        limit:
          type: number
          format: int64
        offset:
          type: number
          format: int64
        totalCount:
          type: number
          format: int64
x-original-swagger-version: null
