openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    terminatorCost:
      maximum: 65535
      minimum: 0
      type: integer
    terminatorPrecedence:
      type: string
      enum:
      - default
      - required
      - failed
    terminatorPrecedenceMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/terminatorPrecedence'
    terminatorCostMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/terminatorCost'
x-original-swagger-version: null
