name: build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

concurrency: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'

      - name: Install Ziti CI
        uses: netfoundry/ziti-ci@v1

      - name: Build and Test
        run: go test ./...
